[2022-07-13 00:55:14,663] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2022-07-13T00:55:11.357468+00:00 [queued]>
[2022-07-13 00:55:14,680] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2022-07-13T00:55:11.357468+00:00 [queued]>
[2022-07-13 00:55:14,681] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-13 00:55:14,681] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-07-13 00:55:14,681] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-13 00:55:14,706] {taskinstance.py:1397} INFO - Executing <Task(HttpSensor): is_api_available> on 2022-07-13 00:55:11.357468+00:00
[2022-07-13 00:55:14,712] {standard_task_runner.py:52} INFO - Started process 10992 to run task
[2022-07-13 00:55:14,717] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'manual__2022-07-13T00:55:11.357468+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpca60sg3k', '--error-file', '/tmp/tmp2298mo9p']
[2022-07-13 00:55:14,718] {standard_task_runner.py:80} INFO - Job 15: Subtask is_api_available
[2022-07-13 00:55:14,815] {task_command.py:371} INFO - Running <TaskInstance: user_processing.is_api_available manual__2022-07-13T00:55:11.357468+00:00 [running]> on host b0c7b58a654d
[2022-07-13 00:55:14,920] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2022-07-13T00:55:11.357468+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-13T00:55:11.357468+00:00
[2022-07-13 00:55:14,923] {http.py:97} INFO - Poking: api/
[2022-07-13 00:55:14,938] {base.py:68} INFO - Using connection ID 'user_api' for task execution.
[2022-07-13 00:55:14,939] {http.py:129} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2022-07-13 00:55:15,484] {base.py:301} INFO - Success criteria met. Exiting.
[2022-07-13 00:55:15,503] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20220713T005511, start_date=20220713T005514, end_date=20220713T005515
[2022-07-13 00:55:15,533] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-13 00:55:15,616] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
